name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: 🧪 Run Tests
        uses: stateful/runme-action@v2
        with:
          workflows: |
            test-js
      - name: Push to hub
        env:
          HF_SECRET: ${{ secrets.HF_SECRET }}
          HF_USERNAME: ${{ vars.HF_USERNAME }}
          SPACE_NAME: ${{ vars.SPACE_NAME }}
        run: git push https://$HF_USERNAME:$HF_SECRET@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
